#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int state=0;
task main()
{
	while(!getTouchValue(touch))sleep(300);
	startTask(drive);



}
task drive(){
		while(1){
			switch(state){

		}
		sleep(100);
	}
}

task sense(){
	//test for sonic
	//quiver state
	//test for win
//win state
//test for loss
//loss state
}
