#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(!getTouchValue(touch))sleep(300);
	setMotorSpeed(left,100);
	setMotorSpeed(right,100);



}
